require:
  - rubocop-rspec_rails
  - rubocop-slim

plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - .toys.rb

Rails:
  Enabled: true

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods:
    - touch
    - touch_all

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  AllowInnerSlashes: false
  Exclude:
    - features/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
